//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car with one or more of such properties already exists..
        /// </summary>
        public static string AddingCarNotAllowed {
            get {
                return ResourceManager.GetString("AddingCarNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already confirmed your email address!.
        /// </summary>
        public static string AlreadyConfirmEmail {
            get {
                return ResourceManager.GetString("AlreadyConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot accept this invite.
        /// </summary>
        public static string CannotAcceptInvite {
            get {
                return ResourceManager.GetString("CannotAcceptInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot deny this invite.
        /// </summary>
        public static string CannotDenyInvite {
            get {
                return ResourceManager.GetString("CannotDenyInvite", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Comment not found.
        /// </summary>
        public static string CommentNotFound {
            get {
                return ResourceManager.GetString("CommentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong code or this code is deprecated, try again!.
        /// </summary>
        public static string ConfirmEmailInvalidCode {
            get {
                return ResourceManager.GetString("ConfirmEmailInvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with such email already exists..
        /// </summary>
        public static string EmailAlreadyExists {
            get {
                return ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First you need to confirm your email address.
        /// </summary>
        public static string EmailNotConfirm {
            get {
                return ResourceManager.GetString("EmailNotConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Event doesn&apos;t found.
        /// </summary>
        public static string EventNotFound {
            get {
                return ResourceManager.GetString("EventNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed sending account confirmation email!.
        /// </summary>
        public static string FailedSendEmail {
            get {
                return ResourceManager.GetString("FailedSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect login or password.
        /// </summary>
        public static string IncorrectLoginOrPassword {
            get {
                return ResourceManager.GetString("IncorrectLoginOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid point&apos;s order!.
        /// </summary>
        public static string InvalidOrder {
            get {
                return ResourceManager.GetString("InvalidOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request.
        /// </summary>
        public static string InvalidRequest {
            get {
                return ResourceManager.GetString("InvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token.
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token verification.
        /// </summary>
        public static string InvalidTokenVerification {
            get {
                return ResourceManager.GetString("InvalidTokenVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already confirmed this invitation.
        /// </summary>
        public static string InviteAlreadyAccepted {
            get {
                return ResourceManager.GetString("InviteAlreadyAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This invite not found or it already answered.
        /// </summary>
        public static string InviteNotFound {
            get {
                return ResourceManager.GetString("InviteNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to do this!.
        /// </summary>
        public static string NotEnoughPermissions {
            get {
                return ResourceManager.GetString("NotEnoughPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is already created.
        /// </summary>
        public static string PasswordIsExist {
            get {
                return ResourceManager.GetString("PasswordIsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report not found.
        /// </summary>
        public static string ReportNotFound {
            get {
                return ResourceManager.GetString("ReportNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role not found.
        /// </summary>
        public static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The route has already had invites! You can only decline the invite!.
        /// </summary>
        public static string RouteHasInvites {
            get {
                return ResourceManager.GetString("RouteHasInvites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot send invite to your account.
        /// </summary>
        public static string SendInviteYourself {
            get {
                return ResourceManager.GetString("SendInviteYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error has occured.
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user already accepted your invite.
        /// </summary>
        public static string UserAcceptedInvite {
            get {
                return ResourceManager.GetString("UserAcceptedInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user has already assigned.
        /// </summary>
        public static string UserAlreadyAssigned {
            get {
                return ResourceManager.GetString("UserAlreadyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already has invite, wait for a answer.
        /// </summary>
        public static string UserAlreadyHasInvite {
            get {
                return ResourceManager.GetString("UserAlreadyHasInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with active offers or trips can`t be deleted.
        /// </summary>
        public static string UserCantBeDeleted {
            get {
                return ResourceManager.GetString("UserCantBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User id not found!.
        /// </summary>
        public static string UserIdNotFound {
            get {
                return ResourceManager.GetString("UserIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this username already exist.
        /// </summary>
        public static string UsernameAlreadyExists {
            get {
                return ResourceManager.GetString("UsernameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong code or this code is deprecated, try again!.
        /// </summary>
        public static string WrongResetPasswordCode {
            get {
                return ResourceManager.GetString("WrongResetPasswordCode", resourceCulture);
            }
        }
    }
}
